Repository ForJJJ/DeliverySystem, pull requests merged in 2024-09, with the labels that each got.

#11 [feat] 주문 등록 기능 구현
  com.forj.delivery-system/com.forj.order/.gitignore
  com.forj.delivery-system/com.forj.order/build.gradle
  com.forj.delivery-system/com.forj.order/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.order/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.order/gradlew
  com.forj.delivery-system/com.forj.order/gradlew.bat
  com.forj.delivery-system/com.forj.order/settings.gradle
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/OrderApplication.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/dto/OrderResponseDto.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/enums/OrderEnum.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/model/Order.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/repostiory/OrderRepository.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/Repository/JpaOrderRepository.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/request/OrderRequestDto.java
  com.forj.delivery-system/com.forj.order/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.order/src/test/java/com/forj/order/OrderApplicationTests.java
  com.forj.delivery-system/docker-compose.yml
  com.forj.delivery-system/init-db/create_databases.sql
Labels: 개발

#12 [feat] #5 주문 조회 초기 파일 설정
  com.forj.delivery-system/com.forj.order/.gitignore
  com.forj.delivery-system/com.forj.order/build.gradle
  com.forj.delivery-system/com.forj.order/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.order/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.order/gradlew
  com.forj.delivery-system/com.forj.order/gradlew.bat
  com.forj.delivery-system/com.forj.order/settings.gradle
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/OrderApplication.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/dto/OrderResponseDto.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/enums/OrderEnum.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/model/Order.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/repostiory/OrderRepository.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/Repository/JpaOrderRepository.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/request/OrderRequestDto.java
  com.forj.delivery-system/com.forj.order/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.order/src/test/java/com/forj/order/OrderApplicationTests.java
Labels: 개발

#13 [feat] Order 주문 단건 조회 기능 구현
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/repostiory/OrderRepository.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
Labels: 개발

#14 [feat] Order 주문 수정 기능 구현
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/model/Order.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
Labels: 개발

#15 [feat] #7 초기파일 세팅
  com.forj.delivery-system/com.forj.order/.gitignore
  com.forj.delivery-system/com.forj.order/build.gradle
  com.forj.delivery-system/com.forj.order/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.order/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.order/gradlew
  com.forj.delivery-system/com.forj.order/gradlew.bat
  com.forj.delivery-system/com.forj.order/settings.gradle
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/OrderApplication.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/dto/OrderResponseDto.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/enums/OrderEnum.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/model/Order.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/repostiory/OrderRepository.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/Repository/JpaOrderRepository.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/request/OrderRequestDto.java
  com.forj.delivery-system/com.forj.order/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.order/src/test/java/com/forj/order/OrderApplicationTests.java
Labels: 개발

#16 [feat] Order 주문 삭제 기능 구현
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/model/Order.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
Labels: 개발

#17 [feat] Order 주문 상태 변경 기능 구현
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/dto/OrderResponseDto.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/enums/OrderEnum.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/enums/OrderStatusEnum.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/model/Order.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/request/OrderStatusRequestDto.java
Labels: 개발

#18 [feat] Order 주문 취소 요청 기능 구현
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/model/Order.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/presentation/controller/OrderController.java
Labels: 개발

#29 [feat] 배송 단건 조회 구현 완료
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/response/DeliveryResponseDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/service/DeliveryService.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/model/Delivery.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/repository/DeliveryRepository.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/config/DeliveryApplicationQueueConfig.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/OrderCreatedEvent.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/OrderEventListener.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/presentation/controller/DeliveryController.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/config/OrderApplicationQueueConfig.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/messaging/OrderCreatedEvent.java
Labels: 개발

#37 [refactor] User 회원가입 예외처리 수정
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
Labels: 리팩토링

#39 [feat] Auth 로그인 기능 구현
  com.forj.delivery-system/com.forj.auth/build.gradle
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/request/UserLoginRequestDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/response/UserLoginResponseDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/repository/UserRepository.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/config/SecurityConfig.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/jwt/JwtAuthenticationFilter.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/jwt/JwtAuthorizationFilter.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/jwt/JwtUtil.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/security/UserDetailsImpl.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/security/UserDetailsServiceImpl.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/AuthController.java
  com.forj.delivery-system/com.forj.auth/src/main/resources/application.yml
Labels: 개발

#42 [feat] Hub 모든 허브 조회 구현
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/HubCreateResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/HubInfoResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/HubListResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/repository/HubRepository.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/configuration/HubJacksonConfig.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/repository/HubRepositoryImpl.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/presentation/HubController.java
Labels: 개발

#47 [feat] HubMovement CRUD 구현
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/HubResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/request/HubMovementRequestDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/request/HubMovementUpdateRequestDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/request/HubRequestDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/AddressDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/HubInfoResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/HubListResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/HubMovementInfoResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/HubMovementListResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/NaverDrivingResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/NaverGeoPointResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/RouteDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/Summary.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/TrafastDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubMovementApplicationService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/NaverGeoClient.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/model/Hub.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/model/HubMovement.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/repository/HubMovementRepository.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/service/HubMovementService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/configuration/HubRedisConfig.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/repository/HubMovementRepositoryImpl.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/repository/JPAHubMovementRepository.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/presentation/HubController.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/presentation/HubMovementController.java
  com.forj.delivery-system/com.forj.hub/src/main/resources/data.sql
Labels: 개발

#48 [feat] User : getUser, updateUser 기능 구현
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/request/UserUpdateRequestDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/response/UserGetResponseDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/model/User.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/repository/UserRepository.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/filter/CustomPreAuthFilter.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/UserController.java
  com.forj.delivery-system/com.forj.gateway/src/main/java/com/forj/gateway/infrastructure/filter/LocalJwtAuthenticationFilter.java
  com.forj.delivery-system/com.forj.gateway/src/main/resources/application.yml
Labels: 개발

#49 [refactor] Hub 서비스 클래스 분리로 인한 변경
  com.forj.delivery-system/com.forj.hub/build.gradle
  com.forj.delivery-system/com.forj.hub/gradlew
  com.forj.delivery-system/com.forj.hub/gradlew.bat
  com.forj.delivery-system/com.forj.hub/settings.gradle
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/SecurityContextUserFilter.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubApplicationService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubCacheService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubMovementApplicationService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/service/HubService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/presentation/HubController.java
  com.forj.delivery-system/com.forj.hub/src/main/resources/application.yml
Labels: 리팩토링

#51 [feat] User 유저 검색 기능 구현
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/response/UserSearchResponseDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/repository/UserRepository.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/filter/CustomPreAuthFilter.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/UserController.java
Labels: 개발

#55 [feat] DeliveryAgent CRU 기능 구현
  com.forj.delivery-system/com.forj.auth/build.gradle
  com.forj.delivery-system/com.forj.auth/settings.gradle
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/AuthApplication.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/request/DeliveryAgentRequestDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/response/DeliveryAgentGetResponseDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/model/DeliveryAgent.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/model/DeliveryAgentRole.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/repository/DeliveryAgentRepository.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/repository/JpaDeliveryAgentRepository.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/UserController.java
Labels: 개발

#56 [refactor] ResponseEntity로 반환
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/AuthController.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/UserController.java
Labels: 리팩토링

#57 [feat] Common 모듈 추가
  com.forj.delivery-system/build.gradle
  com.forj.delivery-system/com.forj.common/.gitignore
  com.forj.delivery-system/com.forj.common/build.gradle
  com.forj.delivery-system/com.forj.common/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.common/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.common/gradlew
  com.forj.delivery-system/com.forj.common/gradlew.bat
  com.forj.delivery-system/com.forj.common/settings.gradle
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/CommonApplication.java
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/jpa/BaseEntity.java
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/security/AuditorAwareImpl.java
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/security/CommonSecurityConfig.java
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/security/SecurityContextUserFilter.java
  com.forj.delivery-system/com.forj.common/src/test/java/com/forj/common/CommonApplicationTests.java
  com.forj.delivery-system/com.forj.company/.gitignore
  com.forj.delivery-system/com.forj.company/build.gradle
  com.forj.delivery-system/com.forj.company/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.company/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/CompanyApplication.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/application/dto/request/CompanyRequestDto.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/domain/model/Company.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/domain/model/CompanyType.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/infrastructure/repository/CompanyRepository.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/presentation/CompanyController.java
  com.forj.delivery-system/com.forj.company/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.company/src/test/java/com/forj/company/CompanyApplicationTests.java
  com.forj.delivery-system/com.forj.gateway/src/main/resources/application.yml
  com.forj.delivery-system/settings.gradle
Labels: 개발

#58 [refactor] DeliveryAgent 서비스 분리
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/UserController.java
  com.forj.delivery-system/com.forj.delivery-agent/.gitignore
  com.forj.delivery-system/com.forj.delivery-agent/build.gradle
  com.forj.delivery-system/com.forj.delivery-agent/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.delivery-agent/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.delivery-agent/gradlew
  com.forj.delivery-system/com.forj.delivery-agent/gradlew.bat
  com.forj.delivery-system/com.forj.delivery-agent/settings.gradle
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/DeliveryAgentApplication.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/application/dto/request/DeliveryAgentRequestDto.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/application/dto/response/DeliveryAgentGetResponseDto.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/application/service/DeliveryAgentService.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/domain/model/DeliveryAgent.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/domain/model/DeliveryAgentRole.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/domain/repository/DeliveryAgentRepository.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/infrastructure/config/DeliveryAgentSecurityConfig.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/infrastructure/filter/DeliveryAgentCustomPreAuthFilter.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/infrastructure/repository/JpaDeliveryAgentRepository.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/presentation/controller/DeliveryAgentController.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.delivery-agent/src/test/java/com/forj/delivery_agent/DeliveryAgentApplicationTests.java
  com.forj.delivery-system/com.forj.gateway/src/main/resources/application.yml
Labels: 리팩토링

#62 [refactor] Auth, DeliveryAgent 공통 모듈 적용
  com.forj.delivery-system/com.forj.auth/build.gradle
  com.forj.delivery-system/com.forj.auth/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.auth/gradlew
  com.forj.delivery-system/com.forj.auth/gradlew.bat
  com.forj.delivery-system/com.forj.auth/settings.gradle
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/AuthApplication.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/model/User.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/config/SecurityConfig.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/filter/CustomPreAuthFilter.java
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/security/CommonSecurityConfig.java
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/security/SecurityContextUserFilter.java
  com.forj.delivery-system/com.forj.delivery-agent/build.gradle
  com.forj.delivery-system/com.forj.delivery-agent/gradlew
  com.forj.delivery-system/com.forj.delivery-agent/gradlew.bat
  com.forj.delivery-system/com.forj.delivery-agent/settings.gradle
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/DeliveryAgentApplication.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/domain/model/DeliveryAgent.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/infrastructure/config/DeliveryAgentSecurityConfig.java
  com.forj.delivery-system/com.forj.delivery-agent/src/main/java/com/forj/delivery_agent/infrastructure/filter/DeliveryAgentCustomPreAuthFilter.java
  com.forj.delivery-system/settings.gradle
Labels: 리팩토링

#66 [feat] Slack Bot Message 전송 기능 구현
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/request/UserSignupRequestDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/response/UserGetResponseDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/dto/response/UserSearchResponseDto.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/model/User.java
  com.forj.delivery-system/com.forj.common/src/main/java/com/forj/common/security/SecurityContextUserFilter.java
  com.forj.delivery-system/com.forj.gateway/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.slack-message/.gitignore
  com.forj.delivery-system/com.forj.slack-message/build.gradle
  com.forj.delivery-system/com.forj.slack-message/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.slack-message/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/SlackMessageApplication.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/application/dto/request/SlackMessageRequestDto.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/application/service/SlackService.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/application/service/UserServiceClient.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/domain/model/Slack.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/domain/repository/SlackRepository.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/infrastructure/config/FeignConfig.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/infrastructure/dto/UserDto.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/infrastructure/repository/JpaSlackRepository.java
  com.forj.delivery-system/com.forj.slack-message/src/main/java/com/forj/slack_message/presentation/controller/SlackController.java
  com.forj.delivery-system/com.forj.slack-message/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.slack-message/src/test/java/com/forj/slack_message/SlackMessageApplicationTests.java
  com.forj.delivery-system/settings.gradle
Labels: 개발

#75 [refactor] 전반적인 코드 리팩토링 및 Product쪽 큐 수신 구현
  com.forj.delivery-system/build.gradle
  com.forj.delivery-system/com.forj.delivery/build.gradle
  com.forj.delivery-system/com.forj.delivery/gradlew
  com.forj.delivery-system/com.forj.delivery/gradlew.bat
  com.forj.delivery-system/com.forj.delivery/settings.gradle
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/DeliveryApplication.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/client/CompanyClient.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/client/UserClient.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/request/DeliveryUpdateRequestDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/request/DriverAssignRequestDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/response/CompanyResponseDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/response/DeliveryListResponseDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/response/DeliveryResponseDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/response/UserResponseDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/service/DeliveryAssignService.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/service/DeliveryService.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/enums/DeliveryStatusEnum.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/model/Delivery.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/model/company/Company.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/model/delivery/Delivery.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/repository/CompanyRepository.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/repository/DeliveryRepository.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/domain/service/DeliveryDomainService.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/config/CompanyConfig.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/config/DeliveryConfig.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/config/FeignClientConfig.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/DeliveryCreatedEvent.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/DeliveryHistoryListener.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/DeliveryMessageListener.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/DeliveryMessageProducer.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/DeliveryStatusChangeEvent.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/OrderCreatedEvent.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/OrderEventListener.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/OrderStatusChangeEvent.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/message/DeliveryDeliveryHistoryCompleteMessage.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/message/DeliveryDeliveryHistoryMessage.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/message/DeliveryOrderMessage.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/message/DeliveryProductMessage.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/repository/JpaDeliveryRepository.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/repository/company/JpaCompanyRepository.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/presentation/controller/DeliveryController.java
  com.forj.delivery-system/com.forj.delivery/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/application/service/OrderService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/domain/service/OrderDomainService.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/messaging/OrderMessageListener.java
  com.forj.delivery-system/delivery-history/.gitignore
Labels: 개발, 리팩토링

#77 [feat] queue 모듈 추가 Order쪽만 적용
  com.forj.delivery-system/com.forj.order/build.gradle
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/OrderApplication.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/config/OrderApplicationQueueConfig.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/messaging/OrderMessageListener.java
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/messaging/OrderMessageProducer.java
  com.forj.delivery-system/com.forj.order/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.queue/build.gradle
  com.forj.delivery-system/com.forj.queue/gradle/wrapper/gradle-wrapper.jar
  com.forj.delivery-system/com.forj.queue/gradle/wrapper/gradle-wrapper.properties
  com.forj.delivery-system/com.forj.queue/src/main/java/com/forj/queue/QueueApplication.java
  com.forj.delivery-system/com.forj.queue/src/main/java/com/forj/queue/queue/QueueConfig.java
  com.forj.delivery-system/com.forj.queue/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.queue/src/test/java/com/forj/queue/QueueApplicationTests.java
  com.forj.delivery-system/settings.gradle
Labels: 개발

#78 [feat] queue 모듈 RabbitMQ 사용하는 부분에 전부다 적용
  com.forj.delivery-system/com.forj.delivery/build.gradle
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/DeliveryMessageListener.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/infrastructure/messaging/DeliveryMessageProducer.java
  com.forj.delivery-system/com.forj.delivery/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.order/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.product/build.gradle
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductMessageProducer.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductMessageReceiver.java
  com.forj.delivery-system/com.forj.product/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.queue/src/main/resources/application.yml
  com.forj.delivery-system/delivery-history/src/main/resources/application.yml
Labels: 개발, 리팩토링

#79 [feat] application.yml 수정
  com.forj.delivery-system/com.forj.delivery/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.order/src/main/resources/application.yml
  com.forj.delivery-system/delivery-history/src/main/resources/application.yml
Labels: 리팩토링

#80 [refacter] Product쪽 큐 수정
  com.forj.delivery-system/com.forj.auth/build.gradle
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/DeliveryApplication.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/client/CompanyClient.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/dto/response/CompanyInfoResponseDto.java
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/application/service/DeliveryService.java
  com.forj.delivery-system/com.forj.order/build.gradle
  com.forj.delivery-system/com.forj.order/src/main/java/com/forj/order/infrastructure/messaging/OrderMessageListener.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/ProductApplication.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/configuration/ProductApplicationQueueConfig.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductDeliveryMessage.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductMessageProducer.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductMessageReceiver.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductOrderErrorMessage.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductOrderMessage.java
  com.forj.delivery-system/delivery-history/build.gradle
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/DeliveryHistoryApplication.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/application/service/DeliveryHistoryService.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/domain/model/deliveryhistory/DeliveryHistory.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/domain/model/hubmovement/HubMovement.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/domain/repository/DeliveryHistoryRepository.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/domain/repository/HubMovementRepository.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/infrastructure/config/DeliveryHistoryApplicationQueueConfig.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/infrastructure/messaging/DeliveryCreatedEvent.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/infrastructure/messaging/DeliveryEventListener.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/infrastructure/messaging/DeliveryHistoryDeliveryCompleteMessage.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/infrastructure/messaging/DeliveryHistoryDeliveryMessage.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/infrastructure/messaging/DeliveryStatusChangeEvent.java
  com.forj.delivery-system/delivery-history/src/main/java/com/forj/delivery_history/presentation/controller/DeliveryHistoryController.java
Labels: 개발, 리팩토링

#81 [refactor] Hub 엔티티 - DTO 데이터타입 일치
  com.forj.delivery-system/com.forj.company/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.gateway/src/main/resources/application.yml
  com.forj.delivery-system/com.forj.hub/build.gradle
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/request/HubMovementRequestDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/HubInfoResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/dto/response/HubMovementInfoResponseDto.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubApplicationService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubCacheService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/application/service/HubMovementApplicationService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/model/BaseEntity.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/model/Hub.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/model/HubMovement.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/repository/HubMovementRepository.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/service/HubMovementService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/domain/service/HubService.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/configuration/AsyncConfig.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/configuration/DurationSerializer.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/configuration/HubJacksonConfig.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/repository/HubMovementRepositoryImpl.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/infrastructure/repository/JPAHubMovementRepository.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/presentation/HubController.java
  com.forj.delivery-system/com.forj.hub/src/main/java/com/forj/hub/presentation/HubMovementController.java
  com.forj.delivery-system/com.forj.hub/src/main/resources/data.sql
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/service/ProductApplicationService.java
Labels: 리팩토링

#82 [refactor] Company 엔티티 - DTO 데이터타입 일치
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/application/dto/request/CompanyHubUpdateRequestDto.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/application/dto/request/CompanyRequestDto.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/application/dto/response/CompanyInfoResponseDto.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/application/dto/response/HubInfoResponseDto.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/application/service/CompanyService.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/domain/model/Company.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/infrastructure/repository/CompanyRepository.java
  com.forj.delivery-system/com.forj.company/src/main/java/com/forj/company/presentation/CompanyController.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/dto/request/ProductHubUpdateRequestDto.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/dto/request/ProductRequestDto.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/dto/response/CompanyInfoResponseDto.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/dto/response/HubInfoResponseDto.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/dto/response/ProductInfoResponseDto.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/service/CompanyClient.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/service/HubClient.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/application/service/ProductApplicationService.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/domain/model/Product.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/domain/service/ProductService.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/configuration/ProductApplicationQueueConfig.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/infrastructure/messaging/ProductMessageReceiver.java
  com.forj.delivery-system/com.forj.product/src/main/java/com/forj/product/presentation/ProductController.java
Labels: 리팩토링

#90 [feat] 유저 탈퇴처리 기능 구현
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/application/service/UserService.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/model/User.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/domain/model/UserEntityListener.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/infrastructure/security/UserDetailsServiceImpl.java
  com.forj.delivery-system/com.forj.auth/src/main/java/com/forj/auth/presentation/controller/UserController.java
  com.forj.delivery-system/settings.gradle
Labels: 개발

#91 [feat] Delivery 권한 확인 추가
  com.forj.delivery-system/com.forj.delivery/src/main/java/com/forj/delivery/presentation/controller/DeliveryController.java
Labels: 개발
